services:
  database:
    volumes:
      - ../data/db-prod:/var/lib/postgresql/data

  keycloak:
    environment:
      KC_HOSTNAME: https://keycloak.home.s-kuhn.de
      KEYCLOAK_INTERNAL_URL: http://keycloak:8081
      BACKEND_INTERNAL_URL: http://backend:8080
    ports:
      - "10.0.50.31:8081:8081"

  frontend:
    ports:
      - "10.0.50.31:80:80"
    environment:
      FRONTEND_HOSTNAME: prost.home.s-kuhn.de
      PROST_API_URL: /prost/api
      KEYCLOAK_PUBLIC_URL: https://keycloak.home.s-kuhn.de

  backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KEYCLOAK_INTERNAL_URL: http://keycloak:8081
