services:
  database:
    image: 'postgres:latest'
    container_name: prod_prost_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - database
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    container_name: prod_prost_keycloak
    command: start
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_SPI_SCRIPT_UPLOAD_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: ${POSTGRES_HOST}
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_URL_PORT: ${POSTGRES_PORT}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTP_PORT: 8081
      KEYCLOAK_IMPORT: /opt/keycloak/imports/prost-realm-export.json
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    depends_on:
      - database
    networks:
      - database
      - webproxy
    ports:
      - "8081:8081"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: prod_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - webproxy
    restart: unless-stopped

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/prost_backend:${VERSION_TAG}
    container_name: prod_prost_backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    ports:
      - "80:8080"
    networks:
      - database
      - webproxy
    depends_on:
      - database
      - keycloak
    restart: unless-stopped

networks:
  database:
  webproxy:

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./data/db-prod
      o: bind
