services:
  database:
    image: postgres:latest
    container_name: prost_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - prost-vnet
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  prost-vnet:

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./data/db
      o: bind
