FROM maven:3.8-jdk11 AS builder

WORKDIR /build

COPY keycloak-webhook-event-listener/pom.xml /build/
COPY keycloak-webhook-event-listener/src /build/src

RUN mvn package -DskipTests


FROM quay.io/keycloak/keycloak:26.2.5 AS keycloak-base

WORKDIR /opt/keycloak

COPY --from=builder /build/target/keycloak-webhook-event-listener-*.jar \
                /opt/keycloak/providers/custom-event-listener.jar

RUN /opt/keycloak/bin/kc.sh build