FROM quay.io/keycloak/keycloak:26.1.2
COPY --chmod=644 ./keycloak /opt/keycloak/providers
COPY ./keycloak/prost-realm-export.json /opt/keycloak/data/import/realm-export.json
RUN /opt/keycloak/bin/kc.sh build