services:
  database:
    image: 'postgres:latest'
    container_name: prod_prost_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - database
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    container_name: prod_prost_keycloak
    command: start --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: database
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_URL_PORT: ${POSTGRES_PORT}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - database
    networks:
      - database
      - webproxy
    ports:
      - "8081:8080"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - prost-vnet
    restart: unless-stopped

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/prost_backend:${VERSION_TAG}
    container_name: prod_prost_backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "80:8080"
    networks:
      - database
      - webproxy

networks:
  database:
  webproxy:
    external: true

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ./data/db-prod
      o: bind
