name: Checkstyle
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: "checkstyle-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Install dependencies
        working-directory: server
        run: mvn install -ntp -DskipTests
      - name: Run Spotless
        working-directory: server
        run: mvn spotless:check
