name: Build and Tag Docker Image

on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate GH
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Determine Version
        id: versioning
        run: |
          pr_number=${{ github.event.pull_request.number }}
      
          labels_json=$(gh api \
          repos/${{ github.repository }}/issues/$pr_number/labels \
          --jq '.')
      
          echo "Labels JSON from GH API: $labels_json"
      
          labels=$(echo "$labels_json" | jq -r '.[].name')
      
          if [ -z "$labels" ]; then
            echo "No labels or not JSON parseable."
            exit 1
          fi
      
          bump=""
            for label in $labels; do
              case "$label" in
                "breaking-changes") bump="major" ;;
                "feature")          bump="minor" ;;
                "bugfix")           bump="patch" ;;
            esac
          done

          if [[ -z "$bump" ]]; then
            echo "No valid label found for version bump."
            exit 1
          fi

          current_version=$(git describe --tags --abbrev=0 || echo "0.0.0")
          next_version=$(npx semver $current_version -i $bump)

          echo "next_version=$next_version" >> $GITHUB_ENV

      - name: Update Maven Version
        run: mvn versions:set -DnewVersion=$next_version -f server/pom.xml

      - name: Commit and Push Updated pom.xml
        run: |
          git fetch origin dev
          git checkout dev
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add pom.xml
          git commit -m "Set version to $next_version for PR #${{ github.event.pull_request.number }}"
          git push origin dev

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/prost_backend_dev:${{ env.next_version }}
