name: Synchronize main with dev

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Fetch latest tag from dev
        run: |
          git fetch origin dev --tags
          latest_version=$(git tag -l | sort -V | tail -n 1)
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/prost_backend:${{ env.latest_version }}
            ghcr.io/${{ github.repository_owner }}/prost_backend:latest
