name: Synchronize main with dev

on:
  pull_request:
    branches:
      - main
    types: [closed]

concurrency:
  group: "snyc-main-with-dev-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  sync-main:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Fetch latest tag from dev
        run: |
          git fetch origin dev --tags
          latest_version=$(git tag -l | sort -V | tail -n 1)
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/prost_backend:${{ env.latest_version }}
            ghcr.io/${{ github.repository_owner }}/prost_backend:latest

  deploy-prod:
    environment: prod
    needs: sync-main
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy Docker Files to Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          port: 22
          source: "docker/docker-compose.prod.yaml, docker/Dockerfile.keycloak, docker/keycloak/"
          target: ${{ secrets.DEPLOY_SERVER_PATH }}/docker
          strip_components: 1
          overwrite: true
      - name: Copy needed Files to Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          port: 22
          source: "/keycloak-webhook-event-listener/"
          target: ${{ secrets.DEPLOY_SERVER_PATH }}/keycloak-webhook-event-listener
          strip_components: 1
          overwrite: true

      - name: Log in to the Container registry
        run: |
          export CR_PAT=${{ secrets.GHCR_TOKEN }}
          echo $CR_PAT | docker login ghcr.io -u ${{ secrets.GH_REPOSITORY_OWNER }} --password-stdin

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          port: 22
          debug: true
          script: |
            export PATH=$PATH:/snap/bin
            cd ${{ secrets.DEPLOY_SERVER_PATH }}
            docker image prune -a --force
            cat > .env <<EOF
            VERSION_TAG=${{ secrets.VERSION_TAG }}
            GH_REPOSITORY_OWNER=${{ secrets.GH_REPOSITORY_OWNER }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }}
            KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}
            KC_BOOTSTRAP_ADMIN_USERNAME=${{ secrets.KC_BOOTSTRAP_ADMIN_USERNAME }}
            KC_BOOTSTRAP_ADMIN_PASSWORD=${{ secrets.KC_BOOTSTRAP_ADMIN_PASSWORD }}
            KEYCLOAK_HOSTNAME=${{ secrets.KEYCLOAK_HOSTNAME }}
            BACKEND_HOSTNAME=${{ secrets.BACKEND_HOSTNAME }}
            KEYCLOAK_EVENT_LISTENER_SECRET=${{ secrets.KEYCLOAK_EVENT_LISTENER_SECRET }}
            EOF
            docker compose -f docker-compose.prod.yaml --env-file .env pull
            docker compose -f docker-compose.prod.yaml --env-file .env up --build -d --remove-orphans
